"""
Django settings for emiage_web project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name: str, default: bool = False) -> bool:
    """Lit une variable d'environnement comme booléen."""
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En production, définir DJANGO_SECRET_KEY dans l'environnement (ex: Render).
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure--%*3_6-72fvd^g&imu-f_b9%n1zrd(d=5_ik9^*#5*y$_o2y=b')

# SECURITY WARNING: don't run with debug turned on in production!
# En production, définir DJANGO_DEBUG=False dans l'environnement.
DEBUG = env_bool('DJANGO_DEBUG', default=True)

ALLOWED_HOSTS = os.environ.get(
    'DJANGO_ALLOWED_HOSTS',
    '127.0.0.1,localhost,emiage-gi.onrender.com',
).split(',')

# Autoriser les requêtes HTTPS depuis Render (nécessaire quand DEBUG=False)
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'DJANGO_CSRF_TRUSTED_ORIGINS',
        'https://emiage-gi.onrender.com',
    ).split(',')
    if origin.strip()
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.StudentActivityMiddleware',
]

# Identifiants de l'espace admin personnalisé (à changer en production via env)
ADMIN_LOGIN = os.environ.get('ADMIN_LOGIN', 'Daniki')
ADMIN_PASSWORD = os.environ.get('ADMIN_PASSWORD', 'Daniel87606819')

# ===== Sécurité des sessions =====
# Expansion : la session expire après 14 jours d'inactivité.
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14          # 14 jours
SESSION_SAVE_EVERY_REQUEST = True               # renouvelle la date à chaque requête
SESSION_COOKIE_HTTPONLY = True                  # pas d'accès JS au cookie
SESSION_COOKIE_SAMESITE = 'Lax'
if not DEBUG:
    SESSION_COOKIE_SECURE = True                # uniquement en HTTPS (prod)

ROOT_URLCONF = 'emiage_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'emiage_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# En production (Render), définir DATABASE_URL (PostgreSQL).
# En local, si DATABASE_URL est absent, on retombe sur SQLite (db.sqlite3).

import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'core' / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise : sert les fichiers statiques collectés en production (Render)
# Médias : en local -> disque (media/), en production -> Cloudflare R2 (USE_S3=True)
USE_S3 = env_bool('USE_S3', default=False)

if USE_S3:
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3.S3Storage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
        },
    }

    # Cloudflare R2 (compatible S3)
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
    # Endpoint S3 de R2 : https://<account_id>.r2.cloudflarestorage.com
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'auto')
    # ACL : R2 n'utilise pas d'ACL
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    # Domaine public du bucket (r2.dev ou domaine personnalisé) :
    # s'il est défini, les URLs des fichiers seront https://<domaine>/documents/...
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN') or None
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
        },
    }

# Media files (Uploaded files)
# En local : disque (media/). En production sans R2 : fichiers servis depuis
# un dépôt GitHub via MEDIA_BASE_URL (ex: https://raw.githubusercontent.com/Dani-code17/emiage-media/main/)
MEDIA_BASE_URL = os.environ.get('MEDIA_BASE_URL', '/media/')
MEDIA_URL = MEDIA_BASE_URL if MEDIA_BASE_URL.endswith('/') else MEDIA_BASE_URL + '/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Langue et fuseau horaire
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'UTC'
