"""Questions complémentaires pour atteindre >= 5 par ECUE (L1/L2/L3).

Structure : (niveau, semestre, code UE) -> {nom ECUE : [questions]}
Chaque question : (énoncé, bonne réponse, [mauvaises], difficulté, explication)
"""
EXTRA_QUESTIONS = {
    # ============================ L1 S1 ============================
    ('L1', 'S1', 'UE MATHEMATIQUES 1'): {
        'suites et fonctions': [
            ("Une suite arithmétique de raison 3 : u_0=2, alors u_3 vaut :", "11",
             ["8", "9", "14"], "normal", "u_n = u_0 + n×r : 2 + 3×3 = 11."),
            ("Une suite géométrique de raison 2 : u_0=3, alors u_3 vaut :", "24",
             ["9", "12", "18"], "difficile", "u_n = u_0 × r^n : 3 × 2³ = 24."),
            ("La fonction f(x)=x² est :", "décroissante puis croissante",
             ["strictement croissante", "strictement décroissante", "constante"], "normal",
             "x² diminue sur ]-∞,0] puis augmente sur [0,+∞[."),
        ],
        'Calcul intégral': [
            ("L'intégrale de 0 à 2 de f(x)=x est :", "2",
             ["1", "4", "0"], "normal", "∫₀² x dx = [x²/2]₀² = 2."),
            ("Une primitive de f(x)=3 est :", "3x + C",
             ["x³ + C", "3 + C", "x/3 + C"], "facile", "La dérivée de 3x est 3."),
            ("La dérivée de f(x)=x³ est :", "3x²",
             ["x²", "3x", "x⁴/4"], "facile", "d/dx x³ = 3x²."),
        ],
    },
    ('L1', 'S1', 'UE MATHEMATIQUES 2'): {
        'Elements de Logique': [
            ("La table de vérité de « A OU B » est fausse uniquement quand :", "A et B sont faux",
             ["A est vrai", "B est vrai", "jamais"], "facile", "OU est faux seulement si les deux sont faux."),
            ("« non(non A) » équivaut à :", "A",
             ["non A", "vrai", "faux"], "facile", "La double négation se simplifie en A."),
            ("Une implication A ⇒ B est vraie quand A est fausse :", "toujours",
             ["jamais", "parfois", "uniquement si B est fausse"], "difficile",
             "En logique, une implication à prémisse fausse est vraie."),
        ],
        'Structure Algébrique': [
            ("L'élément neutre de la multiplication est :", "1",
             ["0", "-1", "∞"], "facile", "a × 1 = a pour tout a."),
            ("Dans Z/6Z, l'élément 4 est-il inversible ?", "non",
             ["oui", "dépend", "toujours"], "difficile",
             "4 n'est pas premier avec 6, donc non inversible."),
            ("Un anneau est un ensemble muni de :", "deux lois (addition et multiplication)",
             ["une seule loi", "trois lois", "aucune loi"], "normal",
             "Un anneau possède une addition et une multiplication compatibles."),
        ],
    },
    ('L1', 'S1', 'UE ECONOMIE'): {
        'Economie générale': [
            ("La demande d'un bien dépend notamment de :", "son prix",
             ["la couleur du produit", "la météo uniquement", "rien"], "facile",
             "Le prix est le principal déterminant de la demande."),
            ("L'offre d'un bien augmente quand :", "son prix augmente",
             ["son prix baisse", "les coûts augmentent", "la demande baisse"], "normal",
             "Les producteurs offrent plus quand le prix est plus élevé."),
            ("Le chômage est mesuré par :", "le taux de chômage",
             ["le PIB", "l'inflation", "la balance commerciale"], "facile",
             "Le taux de chômage rapporte les chômeurs à la population active."),
        ],
        'Économie 2': [
            ("La déflation est :", "une baisse générale des prix",
             ["une hausse des prix", "une hausse du PIB", "une baisse du chômage"], "normal",
             "La déflation est l'inverse de l'inflation : les prix baissent."),
            ("Une politique monétaire restrictive vise à :", "réduire la masse monétaire",
             ["augmenter les dépenses publiques", "baisser les impôts", "augmenter les salaires"], "difficile",
             "La politique monétaire restrictive ralentit la création monétaire."),
            ("L'équilibre de marché est atteint quand :", "offre = demande",
             ["offre > demande", "demande > offre", "prix = 0"], "facile",
             "À l'équilibre, la quantité offerte égale la quantité demandée."),
        ],
    },
    ('L1', 'S1', 'UE Organisations des Entreprises'): {
        'Organisations des Entreprises': [
            ("Une entreprise privée appartient à :", "des actionnaires privés",
             ["l'État", "une association", "un syndicat"], "facile",
             "Le capital d'une entreprise privée est détenu par des acteurs privés."),
            ("La fonction « production » transforme :", "les ressources en biens ou services",
             ["les clients en fournisseurs", "les impôts en subventions", "le capital en salaires"], "normal",
             "La production convertit les intrants en extrants."),
            ("L'organigramme représente :", "la structure hiérarchique de l'entreprise",
             ["le bilan comptable", "les ventes", "le marketing"], "facile",
             "L'organigramme montre les relations d'autorité et de responsabilité."),
        ],
    },
    ('L1', 'S1', 'UE Initiation à l\'informatique'): {
        'Initiation à l\'informatique': [
            ("1 Ko (kilo-octet) vaut environ :", "1024 octets",
             ["100 octets", "10 octets", "1 000 000 octets"], "normal",
             "En informatique, 1 Ko = 2¹⁰ = 1024 octets."),
            ("Le disque dur sert à :", "stocker des données de façon permanente",
             ["afficher l'image", "refroidir le processeur", "accélérer le réseau"], "facile",
             "Le disque dur conserve les données même hors tension."),
            ("Le système d'exploitation est :", "le logiciel de base qui gère la machine",
             ["un navigateur", "un antivirus", "un tableur"], "normal",
             "L'OS (Windows, Linux…) gère le matériel et les applications."),
        ],
    },
    ('L1', 'S1', 'UE Initiation à l\'algorithmique'): {
        'Initiation à l\'algorithmique': [
            ("L'instruction « Si condition Alors ... Sinon ... » est une structure :", "conditionnelle",
             ["itérative", "séquentielle", "récursive"], "facile",
             "Le Si/Sinon est la structure conditionnelle."),
            ("La boucle « Pour i de 1 à 10 » exécute le bloc :", "10 fois",
             ["9 fois", "11 fois", "1 fois"], "normal",
             "Les valeurs i=1..10 donnent 10 itérations."),
            ("Un algorithme qui s'exécute en un temps proportionnel à n est en :", "O(n)",
             ["O(1)", "O(n²)", "O(log n)"], "normal",
             "O(n) signifie un coût linéaire en la taille des données."),
        ],
    },
    ('L1', 'S1', 'UE Outils Bureautiques 1'): {
        'Outils Bureautiques 1': [
            ("Dans Excel, la fonction SOMME(A1:A5) additionne :", "les cellules A1 à A5",
             ["les colonnes", "les feuilles", "rien"], "facile",
             "SOMME(A1:A5) totalise les valeurs de A1 à A5."),
            ("Dans Word, un tableau s'insère via l'onglet :", "Insertion",
             ["Accueil", "Références", "Affichage"], "normal",
             "Le menu Insertion contient l'outil Tableau."),
            ("Une présentation PowerPoint se compose de :", "diapositives",
             ["feuilles", "cellules", "pages web"], "facile",
             "PowerPoint organise le contenu en diapositives."),
        ],
    },
    ('L1', 'S1', 'UE Electronique Numérique'): {
        'Electronique Numérique': [
            ("Le binaire 101 vaut en décimal :", "5",
             ["101", "3", "6"], "difficile", "4 + 0 + 1 = 5."),
            ("Un transistor peut fonctionner comme :", "un interrupteur",
             ["un réservoir", "une antenne", "un aimant"], "normal",
             "Le transistor commute ou amplifie le signal."),
            ("Le codage binaire d'un bit peut prendre :", "2 valeurs (0 ou 1)",
             ["10 valeurs", "16 valeurs", "1 valeur"], "facile",
             "Un bit est 0 ou 1."),
        ],
    },

    # ============================ L1 S2 ============================
    ('L1', 'S2', 'UE MATHEMATIQUES 3'): {
        'Calcul matriciel': [
            ("L'addition de deux matrices 2×2 donne :", "une matrice 2×2",
             ["une matrice 4×4", "un scalaire", "impossible"], "facile",
             "On additionne terme à terme : le résultat garde la dimension."),
            ("Le déterminant de la matrice [[a,b],[c,d]] est :", "ad − bc",
             ["ab + cd", "a + d", "ac − bd"], "difficile",
             "det = ad − bc."),
            ("La matrice nulle est :", "l'élément neutre de l'addition matricielle",
             ["l'élément neutre du produit", "une matrice inversible", "la matrice identité"], "normal",
             "M + 0 = M pour toute matrice M."),
        ],
        'Espaces vectoriels': [
            ("Une base d'un espace vectoriel est :", "une famille libre et génératrice",
             ["une famille quelconque", "un seul vecteur", "un sous-espace"], "normal",
             "La base doit être libre (indépendante) et génératrice."),
            ("La dimension de R² est :", "2",
             ["1", "4", "∞"], "facile", "R² est engendré par 2 vecteurs indépendants."),
            ("Le vecteur (1,2) est combinaison de (1,0) et (0,1) :", "oui",
             ["non", "dépend", "impossible"], "normal",
             "(1,2) = 1×(1,0) + 2×(0,1)."),
        ],
        'Géometrie': [
            ("La distance entre (0,0) et (3,4) est :", "5",
             ["7", "1", "12"], "normal", "√(3²+4²) = √25 = 5."),
            ("Un cercle de rayon r a pour aire :", "πr²",
             ["2πr", "πr", "r²"], "facile", "L'aire du disque est πr²."),
            ("Deux droites perpendiculaires ont des pentes dont le produit vaut :", "-1",
             ["1", "0", "2"], "difficile", "Le produit des pentes de deux droites perpendiculaires est -1."),
        ],
    },
    ('L1', 'S2', 'UE PROBABILITES ET STATISTIQUE 1'): {
        'Probabilité': [
            ("La somme des probabilités d'un univers complet vaut :", "1",
             ["0", "100", "∞"], "facile", "Les probabilités se partagent l'univers : total 1."),
            ("Deux événements incompatibles ont une intersection :", "vide",
             ["certaine", "égale à l'univers", "de probabilité 1"], "normal",
             "Ils ne peuvent pas se produire en même temps."),
            ("Lancer un dé : la probabilité d'obtenir un nombre pair est :", "1/2",
             ["1/6", "1/3", "2/3"], "normal", "3 faces paires sur 6 : 3/6 = 1/2."),
        ],
        'Statistique': [
            ("La fréquence d'une valeur est :", "effectif divisé par l'effectif total",
             ["l'effectif total", "la somme", "le maximum"], "facile",
             "f = effectif / total."),
            ("L'écart-type est :", "la racine carrée de la variance",
             ["la moyenne", "la médiane", "le carré de la variance"], "normal",
             "σ = √V."),
            ("Une série avec une très grande valeur aberrante : la moyenne est", "sensible à cette valeur",
             ["insensible", "toujours nulle", "égale à la médiane"], "normal",
             "La moyenne est influencée par les valeurs extrêmes."),
        ],
        'Langage R': [
            ("Dans R, la fonction qui calcule la moyenne est :", "mean()",
             ["sum()", "avg()", "average()"], "normal", "mean(x) donne la moyenne."),
            ("Dans R, « c(1,2,3) » crée :", "un vecteur",
             ["un tableau", "une fonction", "un data frame"], "facile",
             "c() combine les valeurs en un vecteur."),
            ("Un data.frame dans R est :", "une structure en lignes et colonnes",
             ["une fonction", "un graphique", "un package"], "normal",
             "Le data.frame est l'équivalent d'un tableau de données."),
        ],
    },
    ('L1', 'S2', 'UE ALGORITHMIQUE ET PROGRAMMATION'): {
        'Algorithmique': [
            ("Le tri à bulles est un algorithme de tri :", "par échanges successifs",
             ["par insertion", "par fusion", "par hachage"], "normal",
             "Le tri bulle échange les éléments adjacents jusqu'au tri complet."),
            ("Une pile fonctionne selon le principe :", "LIFO (dernier entré, premier sorti)",
             ["FIFO", "aléatoire", "trié"], "difficile",
             "LIFO : dernier arrivé, premier servi."),
            ("Une file fonctionne selon le principe :", "FIFO (premier entré, premier sorti)",
             ["LIFO", "aléatoire", "inversé"], "difficile",
             "FIFO : premier arrivé, premier servi."),
        ],
        'Programmation Java': [
            ("En Java, un tableau se déclare avec :", "int[] tab",
             ["int tab", "table int", "array int"], "facile", "int[] est la syntaxe tableau."),
            ("Le mot-clé « final » sur une variable signifie :", "qu'elle ne peut plus être modifiée",
             ["qu'elle est globale", "qu'elle est privée", "qu'elle est nulle"], "normal",
             "final rend la variable constante."),
            ("Une exception en Java permet de :", "gérer les erreurs d'exécution",
             ["accélérer le code", "compiler", "déclarer des variables"], "normal",
             "Les exceptions interceptent les erreurs à l'exécution."),
        ],
    },
    ('L1', 'S2', 'UE Anglais'): {
        'Anglais': [
            ("« I am going to school » — « school » signifie :", "école",
             ["maison", "travail", "hôpital"], "facile", "School = école."),
            ("Le comparatif de « big » est :", "bigger",
             ["more big", "bigest", "most big"], "normal", "Adjectif court : big → bigger."),
            ("« Would you like ... ? » exprime :", "une offre polie",
             ["un ordre", "une obligation", "un regret"], "difficile",
             "Would you like propose quelque chose poliment."),
        ],
    },
    ('L1', 'S2', 'UE Intelligence économique'): {
        'Intelligence économique': [
            ("La veille technologique surveille :", "les innovations et technologies",
             ["les salaires", "la météo", "les impôts"], "normal",
             "La veille technologique suit les évolutions techniques."),
            ("La protection de l'information comprend :", "la sécurité des données et la confidentialité",
             ["la publicité", "le marketing", "la comptabilité"], "normal",
             "Protéger l'information = sécurité, confidentialité, lutte contre l'espionnage."),
            ("L'influence en intelligence économique consiste à :", "faire valoir sa position auprès d'acteurs clés",
             ["acheter des actions", "recruter", "produire"], "difficile",
             "L'influence pousse les décideurs à adopter votre point de vue."),
        ],
    },
    ('L1', 'S2', 'UE Gestion des ressources humaines'): {
        'Gestion des ressources humaines': [
            ("Le recrutement commence par :", "la définition du poste",
             ["la paie", "la formation", "le licenciement"], "normal",
             "On définit d'abord le besoin et le profil du poste."),
            ("L'entretien annuel d'évaluation sert à :", "faire le point sur les performances",
             ["licencier", "augmenter les salaires automatiquement", "clôturer les comptes"], "normal",
             "Il évalue les résultats et fixe des objectifs."),
            ("La formation du personnel vise à :", "développer les compétences",
             ["réduire les effectifs", "augmenter les coûts", "remplacer la paie"], "facile",
             "La formation améliore les compétences des salariés."),
        ],
    },
    ('L1', 'S2', 'UE Atelier de maintenance'): {
        'Atelier de maintenance': [
            ("Une maintenance corrective intervient :", "après la panne",
             ["avant la panne", "chaque semaine", "jamais"], "facile",
             "La maintenance corrective répare après défaillance."),
            ("Le diagnostic d'une panne consiste à :", "identifier la cause du dysfonctionnement",
             ["remplacer tout le matériel", "formater", "jeter l'équipement"], "normal",
             "Diagnostiquer = trouver l'origine de la panne."),
            ("La maintenance prédictive s'appuie sur :", "l'analyse des données de fonctionnement",
             ["le hasard", "la météo", "les ventes"], "difficile",
             "Elle anticipe les pannes grâce aux capteurs et données."),
        ],
    },
    ('L1', 'S2', 'UE Infographie(Montage vidéo,etc..)'): {
        'Infographie(Montage vidéo,etc..)': [
            ("Le format PNG prend en charge :", "la transparence",
             ["les vidéos", "le son", "les animations complexes"], "normal",
             "PNG gère la transparence (canal alpha)."),
            ("Un montage vidéo consiste à :", "assembler et organiser des séquences",
             ["compresser des images", "écrire du code", "créer des tableaux"], "facile",
             "Le montage assemble les plans pour raconter une histoire."),
            ("Le RVB (RGB) est un modèle de couleurs :", "additif (écrans)",
             ["soustractif (impression)", "monochrome", "binaire"], "normal",
             "RVB additionne les lumières rouge, verte, bleue sur les écrans."),
        ],
    },
    ('L1', 'S2', 'UE Outils Bureautiques 2'): {
        'Outils Bureautiques 2': [
            ("Le publipostage permet de :", "personnaliser un document pour plusieurs destinataires",
             ["imprimer en masse", "créer des graphiques", "compresser des fichiers"], "normal",
             "Le publipostage fusionne un modèle avec une liste de contacts."),
            ("Dans Excel, un tableau croisé dynamique sert à :", "analyser et synthétiser des données",
             ["saisir du texte", "insérer des images", "envoyer des mails"], "difficile",
             "Le TCD résume de grands volumes de données."),
            ("Le format PDF a pour avantage :", "une mise en page figée et lisible partout",
             ["d'être modifiable facilement", "de compresser la vidéo", "de contenir du code"], "facile",
             "Le PDF conserve la mise en page sur tous les appareils."),
        ],
    },
    ('L1', 'S2', 'UE TECHNIQUE D\'EXPRESSION ET METHODOLOGIE DU TRAVAIL'): {
        "Technique d'expression": [
            ("Un plan dialectique s'organise en :", "thèse, antithèse, synthèse",
             ["introduction, conclusion", "début, milieu, fin", "analyse, détail, liste"], "normal",
             "Le plan dialectique confronte les points de vue."),
            ("Le résumé d'un texte doit :", "être fidèle au texte et plus court",
             ["ajouter des opinions", "copier des passages", "changer le sens"], "facile",
             "Résumer = condenser sans trahir le contenu."),
            ("Un compte rendu de réunion mentionne :", "les décisions et les actions à mener",
             ["uniquement les présents", "les opinions personnelles", "la météo"], "normal",
             "Le compte rendu acte les décisions et les responsables."),
        ],
        'Methodologie de travail': [
            ("La méthode de lecture SQ3R comprend :", "survoler, questionner, lire, réciter, réviser",
             ["lire vite une seule fois", "copier le texte", "mémoriser sans comprendre"], "difficile",
             "SQ3R structure la lecture active."),
            ("Planifier ses révisions permet de :", "organiser le travail dans le temps",
             ["travailler au hasard", "tout faire la veille", "abandonner"], "facile",
             "Un planning répartit les efforts et évite le stress."),
            ("Une bibliographie se présente :", "par ordre alphabétique des auteurs",
             ["au hasard", "par taille", "par couleur"], "normal",
             "La bibliographie liste les sources par ordre alphabétique."),
        ],
    },

    # ============================ L2 S3 ============================
    ('L2', 'S3', 'Mathématiques 4'): {
        'Algèbre': [
            ("Le produit scalaire de (1,2) et (3,4) vaut :", "11",
             ["10", "7", "12"], "difficile", "1×3 + 2×4 = 3 + 8 = 11."),
            ("Une matrice symétrique vérifie :", "A = Aᵗ (transposée)",
             ["A = -A", "A² = A", "A est nulle"], "normal",
             "La transposée d'une matrice symétrique est elle-même."),
            ("Le rang d'une matrice est :", "le nombre de lignes indépendantes",
             ["le nombre de colonnes", "sa taille", "son déterminant"], "difficile",
             "Le rang mesure l'indépendance des lignes/colonnes."),
        ],
        'Analyse 3': [
            ("La dérivée de ln(x) est :", "1/x",
             ["x", "ln(x)", "e^x"], "facile", "d/dx ln(x) = 1/x."),
            ("La dérivée de e^x est :", "e^x",
             ["x·e^x", "1", "0"], "facile", "e^x est sa propre dérivée."),
            ("Une fonction convexe a sa dérivée seconde :", "positive",
             ["négative", "nulle", "infinie"], "normal",
             "La convexité se traduit par f'' ≥ 0."),
        ],
    },
    ('L2', 'S3', 'Probabilités et statistique 2'): {
        'Probabilités 2': [
            ("La formule des probabilités totales sert à :", "calculer P(B) à partir d'une partition",
             ["calculer une moyenne", "trier les données", "résoudre une équation"], "difficile",
             "P(B) = Σ P(Aᵢ) × P(B|Aᵢ) sur une partition."),
            ("P(A|B) se lit :", "probabilité de A sachant B",
             ["probabilité de B sachant A", "A et B", "A ou B"], "facile",
             "P(A|B) est la probabilité conditionnelle de A donné B."),
            ("Une variable aléatoire discrète prend :", "un nombre fini ou dénombrable de valeurs",
             ["des valeurs continues", "aucune valeur", "des valeurs négatives uniquement"], "normal",
             "La variable discrète a des valeurs isolées."),
        ],
        'Statistique 2': [
            ("Le coefficient de corrélation est compris entre :", "-1 et 1",
             ["0 et 1", "-∞ et +∞", "0 et 100"], "normal",
             "r ∈ [-1, 1] : 1 corrélation parfaite positive, -1 négative."),
            ("La médiane est robuste car :", "elle résiste aux valeurs extrêmes",
             ["elle dépend de toutes les valeurs", "elle est toujours nulle", "elle est aléatoire"], "normal",
             "La médiane ne dépend pas des valeurs extrêmes."),
            ("L'intervalle de confiance mesure :", "la précision d'une estimation",
             ["la moyenne", "le maximum", "la variance exacte"], "difficile",
             "L'IC encadre l'estimation avec un niveau de confiance."),
        ],
        'Analyse de données': [
            ("Un histogramme représente :", "la distribution d'une variable quantitative",
             ["une relation entre deux variables", "une tendance", "un classement"], "facile",
             "L'histogramme montre la répartition des valeurs."),
            ("Le diagramme en boîte (boxplot) montre :", "médiane, quartiles et valeurs aberrantes",
             ["la moyenne uniquement", "le total", "la fréquence"], "normal",
             "Le boxplot résume la dispersion et détecte les outliers."),
            ("L'analyse de corrélation permet de :", "mesurer le lien entre deux variables",
             ["prédire sans données", "trier", "supprimer des variables"], "normal",
             "Elle quantifie la force du lien linéaire."),
        ],
    },
    ('L2', 'S3', 'Comptabilité generale'): {
        'Modèle comptable': [
            ("Le compte de résultat présente :", "les produits et les charges",
             ["l'actif et le passif", "les salaires", "la trésorerie"], "normal",
             "Le compte de résultat mesure la performance : produits − charges = résultat."),
            ("Le bénéfice est :", "un résultat positif (produits > charges)",
             ["un résultat négatif", "l'actif", "le chiffre d'affaires"], "facile",
             "Bénéfice = produits supérieurs aux charges."),
            ("Le principe de la partie double veut que :", "chaque opération affecte au moins deux comptes",
             ["chaque compte soit unique", "les écritures soient mensuelles", "le débit soit toujours égal au crédit en négatif"], "difficile",
             "Chaque écriture a un débit et un crédit équilibrés."),
        ],
        'Opérations comptables': [
            ("Une facture de vente se comptabilise au :", "crédit du compte client",
             ["débit du compte banque uniquement", "crédit du compte capital", "débit du compte fournisseur"], "difficile",
             "La vente crée une créance client (débit) et un produit (crédit)."),
            ("Le compte 401 représente :", "les fournisseurs",
             ["les clients", "les banques", "le capital"], "normal",
             "401 = comptes fournisseurs."),
            ("La TVA collectée est :", "la TVA facturée aux clients",
             ["la TVA sur les achats", "une taxe locale", "un salaire"], "normal",
             "La TVA collectée est celle que l'entreprise encaisse pour l'État."),
        ],
        'Opérations d\'inventaires': [
            ("Les stocks sont évalués :", "au coût d'acquisition ou à la valeur actuelle",
             ["au prix de vente", "au hasard", "à zéro"], "normal",
             "Les stocks sont valorisés au plus faible du coût et de la valeur de marché."),
            ("Un inventaire physique consiste à :", "compter les biens réels",
             ["réviser les salaires", "clôturer la banque", "négocier avec les clients"], "facile",
             "L'inventaire physique vérifie l'existence des stocks."),
            ("La dotation aux amortissements est une charge :", "non décaissée",
             ["décaissée", "exceptionnelle", "financière"], "difficile",
             "L'amortissement constate l'usure sans sortie de trésorerie."),
        ],
    },
    ('L2', 'S3', 'Programmation orientée objet'): {
        'Fondements de la POO': [
            ("Un objet est :", "une instance d'une classe",
             ["une fonction", "un fichier", "un module"], "facile",
             "L'objet est créé à partir d'une classe."),
            ("L'abstraction consiste à :", "ne montrer que l'essentiel",
             ["cacher le code", "dupliquer", "supprimer des classes"], "normal",
             "L'abstraction expose l'interface sans les détails internes."),
            ("La surcharge (overload) permet :", "plusieurs méthodes de même nom avec des paramètres différents",
             ["deux méthodes identiques", "supprimer une méthode", "renommer une classe"], "difficile",
             "Overload = même nom, signatures différentes."),
        ],
        'POO en Java': [
            ("Le constructeur d'une classe sert à :", "initialiser un objet",
             ["détruire un objet", "compiler", "imprimer"], "facile",
             "Le constructeur initialise l'instance à sa création."),
            ("L'interface en Java définit :", "un contrat de méthodes sans implémentation",
             ["du code exécutable", "une base de données", "un fichier"], "normal",
             "L'interface impose des méthodes que les classes implémentent."),
            ("« public », « private », « protected » sont des :", "modificateurs d'accès",
             ["types de données", "boucles", "opérateurs"], "facile",
             "Ils contrôlent la visibilité des membres."),
        ],
        'outils formels pour l\'informatique': [
            ("Une relation de récurrence définit :", "un terme à partir des précédents",
             ["une boucle infinie", "un fichier", "une table"], "normal",
             "Ex : u_n = u_(n-1) + r."),
            ("La récurrence simple pour calculer n! est :", "n! = n × (n-1)!",
             ["n! = n + (n-1)", "n! = 1/n", "n! = n²"], "difficile",
             "La factorielle se définit par récurrence."),
            ("Un invariant de boucle est :", "une propriété vraie avant et après chaque itération",
             ["une erreur", "un type", "une variable globale"], "difficile",
             "L'invariant aide à prouver la correction des boucles."),
        ],
    },
    ('L2', 'S3', 'Anglais'): {
        'Anglais': [
            ("« Although » introduit :", "une concession",
             ["une cause", "une conséquence", "un exemple"], "normal",
             "Although = bien que (concession)."),
            ("Le futur simple se forme avec :", "will + verbe",
             ["have + participe", "be + -ing", "did + verbe"], "facile",
             "I will study."),
            ("« Must » exprime :", "une obligation",
             ["une possibilité", "un souhait", "une habitude"], "facile",
             "Must = devoir (obligation)."),
        ],
    },

    # ============================ L2 S4 ============================
    ('L2', 'S4', 'Mathématiques 5'): {
        'Arithmétique': [
            ("Le PPCM de 4 et 6 est :", "12",
             ["24", "2", "10"], "normal", "Multiples de 4 : 4,8,12 ; de 6 : 6,12 → 12."),
            ("Un nombre est divisible par 3 si :", "la somme de ses chiffres est divisible par 3",
             ["il se termine par 3", "il est pair", "il se termine par 0"], "facile",
             "Critère de divisibilité par 3."),
            ("La décomposition en facteurs premiers de 60 est :", "2² × 3 × 5",
             ["2 × 30", "6 × 10", "3 × 20"], "normal",
             "60 = 4 × 15 = 2² × 3 × 5."),
        ],
    },
    ('L2', 'S4', 'Données semi-structurées et bases de données'): {
        'Base de données relationnelles': [
            ("L'instruction qui supprime des lignes est :", "DELETE",
             ["DROP", "REMOVE", "CLEAR"], "facile", "DELETE supprime des lignes d'une table."),
            ("Une vue (view) en SQL est :", "une requête enregistrée comme une table virtuelle",
             ["une table physique", "un index", "un trigger"], "difficile",
             "La vue masque la complexité des requêtes."),
            ("La normalisation sert à :", "réduire les redondances et anomalies",
             ["accélérer le réseau", "chiffrer", "compresser"], "normal",
             "La normalisation organise les données proprement."),
        ],
        'Données semi-structurées': [
            ("JSON signifie :", "JavaScript Object Notation",
             ["Java Standard Output", "Joint System Object", "JavaScript Option"], "normal",
             "JSON est un format d'échange léger."),
            ("Dans JSON, les objets sont délimités par :", "des accolades { }",
             ["des parenthèses ( )", "des crochets [ ]", "des guillemets "], "facile",
             "Les objets JSON utilisent { }."),
            ("Une base NoSQL de type document stocke :", "des documents (ex: JSON)",
             ["des tables", "des feuilles", "des fichiers audio"], "normal",
             "Les bases document (MongoDB) stockent des documents."),
        ],
        'base de données et applications': [
            ("Une requête préparée protège contre :", "les injections SQL",
             ["les virus", "les pannes", "le réseau"], "difficile",
             "Les requêtes préparées séparent données et code SQL."),
            ("Un SGBD sert à :", "gérer et interroger des bases de données",
             ["créer des sites", "compiler", "éditer des images"], "facile",
             "Le SGBD (MySQL, PostgreSQL…) gère les données."),
            ("La transaction garantit :", "que l'ensemble des opérations réussit ou échoue ensemble",
             ["que chaque requête est indépendante", "la vitesse", "le chiffrement"], "normal",
             "La transaction assure l'atomicité."),
        ],
    },
    ('L2', 'S4', 'Génie logiciel'): {
        'Atelier de Génie Logiciel': [
            ("Le cycle en V découpe le développement en :", "étapes descendantes et remontantes",
             ["une seule étape", "deux étapes", "des itérations aléatoires"], "normal",
             "Le V relie chaque phase de conception à son test."),
            ("Un cahier des charges décrit :", "les besoins et contraintes du projet",
             ["le code final", "les salaires", "les machines"], "facile",
             "Le cahier des charges formalise le besoin client."),
            ("Le test unitaire vérifie :", "une unité de code isolée",
             ["tout le système", "le réseau", "la base entière"], "facile",
             "Le test unitaire teste une fonction/méthode."),
        ],
        'Initiation au Langage SCALA': [
            ("Une fonction scala « val » définit :", "une valeur immuable",
             ["une variable mutable", "une classe", "un package"], "normal",
             "val est immuable, var est mutable."),
            ("Scala s'exécute sur :", "la JVM",
             ["le navigateur uniquement", "le BIOS", "Android uniquement"], "normal",
             "Scala compile vers la JVM (compatible Java)."),
            ("Un « case class » en Scala sert à :", "créer des structures immuables avec pattern matching",
             ["déclarer une variable", "importer un package", "lancer un thread"], "difficile",
             "Les case classes facilitent le matching et l'immutabilité."),
        ],
    },
    ('L2', 'S4', 'Initiation Python'): {
        'Application à la cryptographie': [
            ("Le chiffrement asymétrique utilise :", "une clé publique et une clé privée",
             ["une seule clé", "aucune clé", "trois clés"], "normal",
             "La paire clé publique/privée permet chiffrement et signature."),
            ("RSA repose sur :", "la difficulté de factoriser de grands nombres",
             ["le tri", "les graphes", "les matrices"], "difficile",
             "RSA se base sur la factorisation des grands nombres premiers."),
            ("Une fonction de hachage produit :", "une empreinte de taille fixe",
             ["un chiffrement réversible", "une clé privée", "un fichier"], "normal",
             "Le hash (SHA-256…) donne une empreinte fixe non réversible."),
        ],
    },
    ('L2', 'S4', 'Programmation sous windows'): {
        'Programmation C#': [
            ("C# s'exécute sur la plateforme :", ".NET",
             ["JVM uniquement", "Node", "Flash"], "facile", "C# est le langage de .NET."),
            ("Le mot-clé « var » en C# déclare :", "une variable à type inféré",
             ["une constante", "une classe", "un espace de noms"], "normal",
             "var déduit le type à la compilation."),
            ("Une classe « static » en C# :", "ne peut pas être instanciée",
             ["crée beaucoup d'objets", "est toujours privée", "est virtuelle"], "difficile",
             "Une classe static ne sert qu'à des membres statiques."),
        ],
        'Programmation VBA': [
            ("En VBA, « MsgBox » affiche :", "une boîte de message",
             ["un fichier", "une feuille", "un graphique"], "facile",
             "MsgBox affiche un message à l'utilisateur."),
            ("Une macro VBA est :", "une procédure automatisée",
             ["un virus", "une feuille de calcul", "un graphique"], "normal",
             "La macro exécute des actions automatisées dans Office."),
            ("« Sub » en VBA définit :", "une procédure qui ne retourne pas de valeur",
             ["une fonction qui retourne", "une classe", "un module"], "normal",
             "Sub exécute des actions ; Function retourne une valeur."),
        ],
    },
    ('L2', 'S4', 'Programmation web'): {
        'Programmation web': [
            ("Un lien hypertexte se crée avec la balise :", "<a>",
             ["<link>", "<href>", "<url>"], "facile", "La balise <a href='...'> crée un lien."),
            ("Le protocole HTTP utilise les requêtes et :", "les réponses",
             ["les fichiers", "les sessions", "les cookies uniquement"], "facile",
             "HTTP est un échange requête/réponse."),
            ("« Responsive design » signifie :", "le site s'adapte à l'écran",
             ["le site est rapide", "le site est sécurisé", "le site est statique"], "normal",
             "Le design responsive s'adapte aux tailles d'écran."),
        ],
    },
    ('L2', 'S4', 'Contrôle budgétaire'): {
        'Contrôle budgétaire': [
            ("Le budget de trésorerie prévoit :", "les encaissements et décaissements",
             ["les salaires uniquement", "le bilan", "les impôts"], "normal",
             "Il anticipe les flux de trésorerie."),
            ("Un centre de responsabilité est :", "une unité avec des objectifs et des moyens",
             ["un service comptable", "un immeuble", "un logiciel"], "difficile",
             "Chaque centre est responsable de son budget."),
            ("L'analyse des écarts permet de :", "comprendre les différences prévu/réalisé",
             ["supprimer le budget", "augmenter les salaires", "clôturer"], "normal",
             "Elle explique les écarts de volume, prix et coût."),
        ],
    },
    ('L2', 'S4', 'Projet'): {
        'Projet': [
            ("Un projet se distingue d'une opération courante par :", "son caractère unique et temporaire",
             ["sa durée infinie", "sa répétition", "l'absence d'objectif"], "normal",
             "Le projet est unique, limité dans le temps, avec des livrables."),
            ("Le chef de projet est responsable :", "de l'atteinte des objectifs",
             ["du marketing", "de la comptabilité uniquement", "du recrutement de tous"], "normal",
             "Il pilote délais, coûts et qualité."),
            ("Un diagramme de Gantt visualise :", "le planning des tâches",
             ["les salaires", "le bilan", "les risques financiers"], "facile",
             "Le Gantt montre les tâches sur une frise temporelle."),
            ("La matrice SWOT analyse :", "forces, faiblesses, opportunités, menaces",
             ["coûts, bénéfices", "entrées, sorties", "clients, fournisseurs"], "difficile",
             "SWOT synthétise l'environnement interne et externe."),
        ],
    },

    # ============================ L3 S5 ============================
    ('L3', 'S5', 'ALGORITHMIQUE DES GRAPHES'): {
        'ALGORITHMIQUE DES GRAPHES': [
            ("L'algorithme de Kruskal calcule :", "l'arbre couvrant de poids minimal",
             ["le plus court chemin", "le tri", "la fermeture transitive"], "difficile",
             "Kruskal construit un arbre couvrant minimal."),
            ("Un graphe connexe a :", "un chemin entre toute paire de sommets",
             ["aucun sommet", "des cycles uniquement", "un seul sommet"], "normal",
             "La connexité garantit l'accessibilité entre sommets."),
            ("Le parcours en profondeur (DFS) utilise :", "une pile (récursivité)",
             ["une file", "un tas", "un tableau trié"], "normal",
             "DFS explore en profondeur avec une pile."),
        ],
    },
    ('L3', 'S5', 'BASE DE DONNEES AVANCEES'): {
        'BASE DE DONNEES AVANCEES': [
            ("Une procédure stockée est :", "du code SQL enregistré dans la base",
             ["un index", "une table", "un déclencheur uniquement"], "normal",
             "Les procédures stockées encapsulent la logique SQL."),
            ("Un déclencheur (trigger) s'exécute :", "automatiquement sur un événement",
             ["manuellement", "une fois par jour", "sur demande"], "difficile",
             "Le trigger réagit aux INSERT/UPDATE/DELETE."),
            ("La sauvegarde (backup) sert à :", "restaurer les données en cas de perte",
             ["accélérer les requêtes", "créer des index", "répliquer en temps réel"], "facile",
             "Le backup protège contre la perte de données."),
        ],
    },
    ('L3', 'S5', 'COMPTABILITE ANALYTIQUE'): {
        'COMPTABILITE ANALYTIQUE': [
            ("Le coût de revient comprend :", "tous les coûts liés à un produit",
             ["uniquement les matières", "les impôts", "la trésorerie"], "normal",
             "Le coût de revient totalise matières, main-d'œuvre et charges."),
            ("La marge est :", "le prix de vente moins le coût",
             ["le coût plus les impôts", "le chiffre d'affaires", "le bénéfice net toujours"], "difficile",
             "Marge = prix de vente − coût."),
            ("Un centre de coûts :", "accumule des charges pour analyse",
             ["génère des produits", "est un client", "est un fournisseur"], "normal",
             "Le centre de coûts regroupe des charges homogènes."),
        ],
    },
    ('L3', 'S5', 'COURS DE PROGRAMMATION'): {
        'COURS DE PROGRAMMATION': [
            ("La compilation transforme :", "le code source en code exécutable",
             ["le code en données", "le code en documentation", "les données en code"], "facile",
             "Le compilateur produit le programme exécutable."),
            ("Un débogueur permet de :", "exécuter pas à pas et inspecter",
             ["compiler plus vite", "créer des interfaces", "stocker les données"], "normal",
             "Le débogueur aide à trouver les erreurs."),
            ("Une variable globale est accessible :", "partout dans le programme",
             ["uniquement dans une fonction", "uniquement dans une boucle", "nulle part"], "normal",
             "La variable globale a une portée totale."),
        ],
    },
    ('L3', 'S5', 'PROGRAMMATION LINEAIRE'): {
        'PROGRAMMATION LINEAIRE': [
            ("Une contrainte linéaire est une :", "inégalité ou égalité linéaire",
             ["fonction exponentielle", "condition non linéaire", "donnée statistique"], "normal",
             "Les contraintes sont des relations linéaires sur les variables."),
            ("La solution optimale d'un problème de PL se trouve :", "en un sommet de la région admissible",
             ["au centre", "n'importe où", "en dehors"], "difficile",
             "Le simplexe explore les sommets du polyèdre admissible."),
            ("Un problème de PL à deux variables se résout graphiquement :", "oui",
             ["non", "uniquement à 3 variables", "jamais"], "facile",
             "À deux variables, la région admissible est dessinable."),
        ],
    },
    ('L3', 'S5', 'PROGRAMMATION WEB CLIENT'): {
        'PROGRAMMATION WEB CLIENT': [
            ("Le « client » dans le web est :", "le navigateur de l'utilisateur",
             ["le serveur", "la base de données", "le routeur"], "facile",
             "Le client est le navigateur qui affiche la page."),
            ("Le stockage local (localStorage) permet de :", "garder des données dans le navigateur",
             ["stocker côté serveur", "compiler", "créer des cookies de session uniquement"], "normal",
             "localStorage persiste les données du navigateur."),
            ("Un framework JavaScript front-end est :", "React, Vue ou Angular",
             ["Django", "Spring", "Laravel"], "facile",
             "Ces frameworks structurent le front-end."),
        ],
    },
    ('L3', 'S5', 'SYSTEME D\'EXPLOITATION'): {
        "SYSTEME D'EXPLOITATION": [
            ("L'ordonnanceur (scheduler) gère :", "l'allocation du processeur aux processus",
             ["les fichiers", "le réseau", "l'impression"], "normal",
             "L'ordonnancement décide quel processus s'exécute."),
            ("La mémoire virtuelle permet :", "d'utiliser le disque comme extension de la RAM",
             ["d'accélérer le CPU", "de chiffrer", "de compresser"], "difficile",
             "La mémoire virtuelle pallie le manque de RAM."),
            ("Un interblocage (deadlock) est :", "deux processus qui s'attendent mutuellement",
             ["une erreur de compilation", "un fichier corrompu", "un virus"], "difficile",
             "Le deadlock bloque les processus en attente circulaire."),
        ],
    },
    ('L3', 'S5', 'UNIX_C'): {
        'UNIX_C': [
            ("La commande qui change de répertoire est :", "cd",
             ["ls", "mkdir", "pwd"], "facile", "cd = change directory."),
            ("Un pointeur en C déclaré « int *p » stocke :", "l'adresse d'un entier",
             ["un entier", "un fichier", "une chaîne"], "normal",
             "p contient l'adresse d'une zone contenant un int."),
            ("La commande qui affiche le répertoire courant est :", "pwd",
             ["ls", "cd", "rm"], "facile", "pwd = print working directory."),
        ],
    },

    # ============================ L3 S6 ============================
    ('L3', 'S6', 'ANALYSE DE DONNEES'): {
        'ANALYSE DE DONNEES': [
            ("Le coefficient R² mesure :", "la qualité de l'ajustement du modèle",
             ["le nombre de données", "la variance", "la médiane"], "difficile",
             "R² indique la part de variance expliquée."),
            ("Une analyse de variance (ANOVA) compare :", "les moyennes de plusieurs groupes",
             ["les médianes", "les variances exactes", "les corrélations"], "difficile",
             "L'ANOVA teste si les moyennes diffèrent significativement."),
            ("Le nettoyage des données consiste à :", "traiter les valeurs manquantes et aberrantes",
             ["supprimer toutes les données", "ajouter des données", "trier uniquement"], "normal",
             "Le nettoyage prépare des données fiables."),
        ],
    },
    ('L3', 'S6', 'ANGLAIS'): {
        'ANGLAIS': [
            ("« However » signifie :", "cependant",
             ["de plus", "enfin", "donc"], "normal", "However introduit une opposition."),
            ("« To be able to » signifie :", "pouvoir (être capable de)",
             ["devoir", "vouloir", "savoir que"], "difficile",
             "Be able to exprime la capacité."),
            ("Un « abstract » d'un article est :", "un résumé",
             ["une conclusion", "une annexe", "une référence"], "facile",
             "L'abstract résume l'article."),
        ],
    },
    ('L3', 'S6', 'ENVIRONNEMENT JURIDIQUE'): {
        'ENVIRONNEMENT JURIDIQUE': [
            ("Le RGPD protège :", "les données personnelles des citoyens",
             ["les brevets", "les marques", "les contrats de travail"], "normal",
             "Le RGPD encadre le traitement des données personnelles."),
            ("Un brevet protège :", "une invention technique",
             ["une œuvre littéraire", "une marque", "un nom de domaine"], "normal",
             "Le brevet protège l'invention industrielle."),
            ("Le droit d'auteur protège :", "les œuvres de l'esprit",
             ["les inventions", "les marques", "les brevets"], "facile",
             "Le droit d'auteur couvre les créations artistiques et logicielles."),
        ],
    },
    ('L3', 'S6', 'FILE D\'ATTENTE ET GESTION DE STOCKS'): {
        "FILE D'ATTENTE ET GESTION DE STOCKS": [
            ("La quantité économique de commande (Wilson) minimise :", "le coût total de gestion des stocks",
             ["le coût de production", "les salaires", "le transport"], "difficile",
             "Wilson équilibre coût de commande et coût de stockage."),
            ("Le stock de sécurité protège contre :", "les ruptures de stock",
             ["les vols", "les impôts", "la surproduction"], "facile",
             "Le stock de sécurité absorbe les aléas."),
            ("Dans une file M/M/1, les arrivées suivent :", "un processus de Poisson",
             ["une loi normale", "une loi uniforme", "aucune loi"], "difficile",
             "M/M/1 suppose des arrivées poissonniennes."),
        ],
    },
    ('L3', 'S6', 'GENIE LOGICIEL JAVA'): {
        'GENIE LOGICIEL JAVA': [
            ("Maven sert à :", "automatiser la construction du projet",
             ["tester uniquement", "styliser", "gérer le réseau"], "normal",
             "Maven compile, teste et empaquette le projet."),
            ("Un framework de persistance Java est :", "Hibernate / JPA",
             ["Spring MVC seul", "JUnit", "Log4j"], "difficile",
             "JPA/Hibernate mappe les objets aux tables."),
            ("Spring Boot permet de :", "créer des applications Java rapidement",
             ["créer des graphiques", "gérer les emails", "compiler le CSS"], "normal",
             "Spring Boot simplifie la configuration des applications."),
        ],
    },
    ('L3', 'S6', 'GESTION FINANCIERE'): {
        'GESTION FINANCIERE': [
            ("Le TRI est :", "le taux qui annule la VAN",
             ["le taux d'inflation", "le taux de change", "le taux d'imposition"], "difficile",
             "Le TRI est le taux de rentabilité interne du projet."),
            ("Le fonds de roulement (FR) = :", "ressources stables − emplois stables",
             ["actif − passif", "recettes − dépenses", "capital − dettes"], "difficile",
             "Le FR finance le cycle d'exploitation."),
            ("La trésorerie nette = :", "fonds de roulement − besoin en fonds de roulement",
             ["bénéfice + amortissements", "ventes − achats", "actif circulant"], "difficile",
             "TN = FR − BFR."),
        ],
    },
    ('L3', 'S6', 'INTERNET-INTRANET'): {
        'INTERNET-INTRANET': [
            ("Un extranet est :", "un réseau privé étendu à des partenaires",
             ["un réseau public", "un navigateur", "un moteur de recherche"], "normal",
             "L'extranet ouvre l'intranet à des tiers autorisés."),
            ("Le protocole HTTPS sécurise :", "les échanges entre navigateur et serveur",
             ["le stockage", "l'impression", "le calcul"], "facile",
             "HTTPS chiffre la communication."),
            ("Un VPN permet de :", "créer un tunnel chiffré sur Internet",
             ["accélérer le téléchargement", "bloquer les publicités", "créer des sites"], "normal",
             "Le VPN sécurise la connexion distante."),
        ],
    },
    ('L3', 'S6', 'PROGRAMMATION D\'APPLICATION'): {
        "PROGRAMMATION D'APPLICATION": [
            ("Le JSON est souvent utilisé pour :", "échanger des données entre client et serveur",
             ["styliser", "compiler", "dessiner"], "facile",
             "JSON est le format d'échange standard des API."),
            ("Un endpoint API est :", "une URL qui expose une ressource",
             ["un serveur physique", "une base de données", "un navigateur"], "normal",
             "Chaque endpoint correspond à une opération."),
            ("L'authentification par jeton (token) :", "identifie l'utilisateur sans session serveur",
             ["stocke le mot de passe en clair", "désactive la sécurité", "bloque les requêtes"], "difficile",
             "Le token (JWT) est vérifié par le serveur à chaque requête."),
        ],
    },
    ('L3', 'S6', 'RESEAU'): {
        'RESEAU': [
            ("Le DNS transforme :", "un nom de domaine en adresse IP",
             ["une IP en données", "un fichier en paquet", "un email en spam"], "facile",
             "Le DNS résout les noms en adresses."),
            ("Le masque de sous-réseau 255.255.255.0 autorise :", "256 adresses (dont réseau et broadcast)",
             ["16 adresses", "65536 adresses", "1 adresse"], "normal",
             "Un /24 donne 254 adresses utilisables."),
            ("Le routage consiste à :", "acheminer les paquets entre réseaux",
             ["créer des fichiers", "afficher des pages", "chiffrer"], "normal",
             "Le routeur choisit le chemin des paquets."),
        ],
    },
    ('L3', 'S6', 'THEORIE DU LANGUAGE'): {
        'THEORIE DU LANGUAGE': [
            ("Un langage régulier peut être reconnu par :", "un automate fini",
             ["une machine de Turing universelle", "une grammaire non contextuelle", "un parseur XML"], "normal",
             "Les langages réguliers = automates finis."),
            ("La hiérarchie de Chomsky classe les langages en :", "4 niveaux",
             ["2 niveaux", "10 niveaux", "3 niveaux"], "difficile",
             "Hiérarchie : réguliers, non contextuels, contextuels, récursifs."),
            ("Un analyseur syntaxique (parser) vérifie :", "la conformité à la grammaire",
             ["le sens du code", "les performances", "la mémoire"], "normal",
             "Le parser contrôle la syntaxe du programme."),
        ],
    },
    ('L3', 'S6', 'UML'): {
        'UML': [
            ("Le diagramme de séquence montre :", "les échanges de messages dans le temps",
             ["les classes", "le réseau", "les coûts"], "normal",
             "Le diagramme de séquence illustre les interactions ordonnées."),
            ("Une association en UML relie :", "deux classes",
             ["deux méthodes", "deux packages", "deux serveurs"], "facile",
             "L'association exprime une relation entre classes."),
            ("Le diagramme de cas d'utilisation identifie :", "les acteurs et les fonctionnalités",
             ["les tables", "les algorithmes", "les coûts"], "facile",
             "Il décrit qui fait quoi dans le système."),
        ],
    },
}

