# Generated by Django 5.2.5 on 2025-09-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('COURS', 'Cours'), ('TD_TP', 'TD/TP'), ('EXAMS', 'Anciens Sujets'), ('MAQUETTES', 'Maquettes')], max_length=20, verbose_name='Catégorie')),
                ('level', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=2, verbose_name='Niveau')),
                ('semester', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2')], max_length=2, verbose_name='Semestre')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Fichier')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-upload_date'],
            },
        ),
    ]
