# Generated by Django 5.2.6 on 2025-09-18 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_document_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Code ECUE')),
                ('name', models.CharField(max_length=200, verbose_name='Nom ECUE')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug ECUE')),
            ],
            options={
                'verbose_name': 'ECUE',
                'verbose_name_plural': 'ECUEs',
                'ordering': ['ue__code', 'name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='ecue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.ecue', verbose_name='ECUE'),
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code UE')),
                ('name', models.CharField(max_length=200, verbose_name='Nom UE')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug UE')),
                ('level', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=2, verbose_name='Niveau')),
                ('semester', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('S3', 'Semestre 3'), ('S4', 'Semestre 4'), ('S5', 'Semestre 5'), ('S6', 'Semestre 6'), ('S7', 'Semestre 7'), ('S8', 'Semestre 8'), ('S9', 'Semestre 9'), ('S10', 'Semestre 10')], max_length=3, verbose_name='Semestre')),
            ],
            options={
                'verbose_name': 'UE',
                'verbose_name_plural': 'UEs',
                'ordering': ['level', 'semester', 'code'],
                'unique_together': {('level', 'semester', 'code')},
            },
        ),
        migrations.AddField(
            model_name='ecue',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecues', to='core.ue', verbose_name='UE'),
        ),
        migrations.AlterUniqueTogether(
            name='ecue',
            unique_together={('ue', 'code', 'name')},
        ),
    ]
