# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003b_alter_ue_code'),
    ]

    operations = [
        # Les chemins de fichiers peuvent dépasser 100 caractères (valeur par
        # défaut de FileField), ex: 195 pour certains documents L2/L3.
        # PostgreSQL impose la longueur déclarée (contrairement à SQLite).
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=255, upload_to='documents/', verbose_name='Fichier'),
        ),
    ]
