# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ecue_document_ecue_ue_ecue_ue_and_more'),
    ]

    operations = [
        # Certains codes d'UE dépassent 50 caractères (ex: "UE TECHNIQUE
        # D'EXPRESSION ET METHODOLOGIE DU TRAVAIL" = 52). PostgreSQL impose la
        # longueur déclarée (contrairement à SQLite) : la colonne doit être
        # élargie AVANT la migration de données 0004 qui insère ces codes.
        migrations.AlterField(
            model_name='ue',
            name='code',
            field=models.CharField(max_length=200, verbose_name='Code UE'),
        ),
    ]
