# Generated by Django 5.2.6 on 2025-09-27 09:27

from django.db import migrations


def attach_documents_to_ecue(apps, schema_editor):
    """Rattacher les documents aux bonnes ECUE"""
    Document = apps.get_model('core', 'Document')
    UE = apps.get_model('core', 'UE')
    ECUE = apps.get_model('core', 'ECUE')
    
    print('🔧 Rattachement des documents aux ECUE...')
    
    # Créer les UE et ECUE si elles n'existent pas
    ues_data = [
        # S1
        ('UE Outils Bureautiques 1', 'Outils Bureautiques 1', 'L1', 'S1', ['Outils Bureautiques 1']),
        ('UE Electronique Numérique', 'Electronique Numérique', 'L1', 'S1', ['Electronique Numérique']),
        ('UE Initiation à l\'informatique', 'Initiation à l\'informatique', 'L1', 'S1', ['Initiation à l\'informatique']),
        ('UE Initiation à l\'algorithmique', 'Initiation à l\'algorithmique', 'L1', 'S1', ['Initiation à l\'algorithmique']),
        ('UE ECONOMIE', 'ECONOMIE', 'L1', 'S1', ['Economie générale']),
        ('UE MATHEMATIQUES 1', 'MATHEMATIQUES 1', 'L1', 'S1', ['suites et fonctions', 'Calcul intégral']),
        ('UE MATHEMATIQUES 2', 'MATHEMATIQUES 2', 'L1', 'S1', ['Elements de Logique', 'Structure Algébrique']),
        # S2
        ('UE Anglais', 'Anglais', 'L1', 'S2', ['Anglais']),
        ('UE Intelligence économique', 'Intelligence économique', 'L1', 'S2', ['Intelligence économique']),
        ('UE Gestion des ressources humaines', 'Gestion des ressources humaines', 'L1', 'S2', ['Gestion des ressources humaines']),
        ('UE Infographie(Montage vidéo,etc..)', 'Infographie(Montage vidéo,etc..)', 'L1', 'S2', ['Infographie(Montage vidéo,etc..)']),
        ('UE Atelier de maintenance', 'Atelier de maintenance', 'L1', 'S2', ['Atelier de maintenance']),
        ('UE MATHEMATIQUES 3', 'MATHEMATIQUES 3', 'L1', 'S2', ['Géometrie', 'Calcul matriciel', 'Espaces vectoriels']),
        ('UE PROBABILITES ET STATISTIQUE 1', 'PROBABILITES ET STATISTIQUE 1', 'L1', 'S2', ['Probabilité', 'Statistique', 'Langage R']),
        ('UE ALGORITHMIQUE ET PROGRAMMATION', 'ALGORITHMIQUE ET PROGRAMMATION', 'L1', 'S2', ['Programmation Java', 'Algorithmique']),
        ('UE TECHNIQUE D\'EXPRESSION ET METHODOLOGIE DU TRAVAIL', 'TECHNIQUE D\'EXPRESSION ET METHODOLOGIE DU TRAVAIL', 'L1', 'S2', ['Methodologie de travail', 'Technique d\'expression']),
    ]
    
    for code, name, level, semester, ecues in ues_data:
        ue, _ = UE.objects.get_or_create(code=code, name=name, level=level, semester=semester)
        for ecue_name in ecues:
            ECUE.objects.get_or_create(name=ecue_name, ue=ue)
    
    # Rattacher les documents
    folder_to_ecue = {
        'Suites et Fonctions': ('UE MATHEMATIQUES 1', 'suites et fonctions'),
        'Calcul intégrale': ('UE MATHEMATIQUES 1', 'Calcul intégral'),
        'Elements de logique': ('UE MATHEMATIQUES 2', 'Elements de Logique'),
        'Structure Algébrique': ('UE MATHEMATIQUES 2', 'Structure Algébrique'),
        'Economie': ('UE ECONOMIE', 'Economie générale'),
        'Initiation a l\'informatique': ('UE Initiation à l\'informatique', 'Initiation à l\'informatique'),
        'Initiation à l\'algorithmique': ('UE Initiation à l\'algorithmique', 'Initiation à l\'algorithmique'),
        'Outil Bureautique': ('UE Outils Bureautiques 1', 'Outils Bureautiques 1'),
        'Electronique-Numérique': ('UE Electronique Numérique', 'Electronique Numérique'),
        'Géométrie': ('UE MATHEMATIQUES 3', 'Géometrie'),
        'Matrice-EspaceV': ('UE MATHEMATIQUES 3', 'Calcul matriciel'),
        'Probabilités': ('UE PROBABILITES ET STATISTIQUE 1', 'Probabilité'),
        'Statistique': ('UE PROBABILITES ET STATISTIQUE 1', 'Statistique'),
        'LangageR': ('UE PROBABILITES ET STATISTIQUE 1', 'Langage R'),
        'Algorithmique': ('UE ALGORITHMIQUE ET PROGRAMMATION', 'Algorithmique'),
        'Java': ('UE ALGORITHMIQUE ET PROGRAMMATION', 'Programmation Java'),
        'Intelligence économique': ('UE Intelligence économique', 'Intelligence économique'),
        'GRH': ('UE Gestion des ressources humaines', 'Gestion des ressources humaines'),
        'Infographie': ('UE Infographie(Montage vidéo,etc..)', 'Infographie(Montage vidéo,etc..)'),
        'Anglais': ('UE Anglais', 'Anglais'),
        'Maintenance': ('UE Atelier de maintenance', 'Atelier de maintenance'),
        'EOE': ('UE TECHNIQUE D\'EXPRESSION ET METHODOLOGIE DU TRAVAIL', 'Methodologie de travail'),
    }
    
    updated_count = 0
    for doc in Document.objects.filter(level='L1'):
        file_path = doc.file.name.lower()
        
        # Trouver le dossier correspondant
        folder_name = None
        for folder in folder_to_ecue.keys():
            if folder.lower() in file_path:
                folder_name = folder
                break
        
        if folder_name:
            ue_name, ecue_name = folder_to_ecue[folder_name]
            
            # Déterminer le semestre
            s1_folders = ['Suites et Fonctions', 'Calcul intégrale', 'Elements de logique', 'Structure Algébrique', 'Economie', 'Initiation a l\'informatique', 'Initiation à l\'algorithmique', 'Outil Bureautique', 'Electronique-Numérique']
            semester = 'S1' if folder_name in s1_folders else 'S2'
            
            # Trouver l'ECUE
            try:
                ecue = ECUE.objects.get(
                    name__iexact=ecue_name,
                    ue__name__iexact=ue_name,
                    ue__level='L1',
                    ue__semester=semester
                )
                doc.ecue = ecue
                doc.save()
                updated_count += 1
            except ECUE.DoesNotExist:
                pass
    
    print(f'✅ {updated_count} documents rattachés aux ECUE!')


def reverse_attach_documents(apps, schema_editor):
    """Annuler le rattachement"""
    Document = apps.get_model('core', 'Document')
    Document.objects.filter(level='L1').update(ecue=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ecue_document_ecue_ue_ecue_ue_and_more'),
    ]

    operations = [
        migrations.RunPython(attach_documents_to_ecue, reverse_attach_documents),
    ]
