# Generated by Django 5.2.6 on 2025-09-27 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250927_0927'),
    ]

    operations = [
    ]
