# Generated by Django 5.2.6 on 2025-09-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250927_0933'),
    ]

    operations = [
    ]
