# Generated by Django 5.2.6 on 2026-08-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fix_media_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('level', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=2, verbose_name='Niveau')),
                ('student_id', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Identifiant étudiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['-created_at'],
            },
        ),
    ]
