# Generated by Django 5.2.6 on 2026-08-18 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Identifiant / matricule'),
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, verbose_name='Mois (AAAA-MM)')),
                ('label', models.CharField(max_length=200, verbose_name='Prix / place')),
                ('amount', models.CharField(blank=True, max_length=100, verbose_name='Montant / cadeau')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='Attribué le')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='core.student')),
            ],
            options={
                'verbose_name': 'Prix',
                'verbose_name_plural': 'Prix',
                'ordering': ['-month', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('difficulty', models.CharField(choices=[('facile', 'Facile'), ('normal', 'Normal'), ('difficile', 'Difficile')], default='normal', max_length=10, verbose_name='Difficulté')),
                ('explanation', models.TextField(blank=True, verbose_name='Explication / correction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.ue', verbose_name='UE')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['ue__code', 'difficulty', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Réponse')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Bonne réponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.quizquestion')),
            ],
        ),
        migrations.CreateModel(
            name='StudentStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, verbose_name='Mois (AAAA-MM)')),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='Visites')),
                ('seconds', models.PositiveIntegerField(default=0, verbose_name='Temps (secondes)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.student')),
            ],
            options={
                'verbose_name': 'Statistique',
                'verbose_name_plural': 'Statistiques',
                'unique_together': {('student', 'month')},
            },
        ),
    ]
