# Generated by Django 5.2.6 on 2026-08-18 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_student_password_alter_student_student_id_prize_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(blank=True, max_length=10, verbose_name='Difficulté')),
                ('correct', models.PositiveIntegerField(default=0, verbose_name='Bonnes réponses')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Questions')),
                ('note', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Note /20')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='core.student')),
                ('ue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_attempts', to='core.ue', verbose_name='UE')),
            ],
            options={
                'verbose_name': 'Tentative de quiz',
                'verbose_name_plural': 'Tentatives de quiz',
                'ordering': ['-created_at'],
            },
        ),
    ]
