# Generated by Django 5.2.6 on 2026-08-18 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='ecue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='core.ecue', verbose_name='ECUE'),
        ),
    ]
