# Generated by Django 5.2.6 on 2026-09-19 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_student_birth_date_alter_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JIEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, verbose_name='Édition / année')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='Sous-titre')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('event_time', models.CharField(blank=True, max_length=50, verbose_name='Heure')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('description', models.TextField(blank=True, verbose_name='Description / programme')),
                ('price', models.CharField(blank=True, max_length=100, verbose_name='Prix (ex: 5 000 FCFA)')),
                ('poster_url', models.URLField(blank=True, verbose_name='Affiche (URL)')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='ji/', verbose_name='Affiche (fichier)')),
                ('status', models.CharField(choices=[('avenir', 'À venir'), ('inscriptions', 'Inscriptions ouvertes'), ('passee', 'Passée')], default='avenir', max_length=20, verbose_name='Statut')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Édition mise en avant')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Édition de la JI',
                'verbose_name_plural': 'Éditions de la JI',
                'ordering': ['-order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='JIPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Moyen (ex: Orange Money)')),
                ('number', models.CharField(blank=True, max_length=60, verbose_name='Numéro')),
                ('holder', models.CharField(blank=True, max_length=120, verbose_name='Titulaire')),
                ('instructions', models.CharField(blank=True, max_length=250, verbose_name='Instructions')),
                ('link', models.URLField(blank=True, verbose_name='Lien de paiement')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.jiedition', verbose_name='Édition')),
            ],
            options={
                'verbose_name': 'Moyen de paiement JI',
                'verbose_name_plural': 'Moyens de paiement JI',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JIPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, verbose_name='Photo (URL)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ji/', verbose_name='Photo (fichier)')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.jiedition', verbose_name='Édition')),
            ],
            options={
                'verbose_name': 'Photo JI',
                'verbose_name_plural': 'Photos JI',
                'ordering': ['order', 'id'],
            },
        ),
    ]
